### ISSUE TITLE
Custom rule does not work

### ISSUE THREAD

**Issue by yene** [brittonhayes/pillager#71]
**Describe the bug**
The rules.toml does not seem to work for me, I do the following.

**To Reproduce**
1. create rules.toml
```toml
title = "rules"

[[rules]]
id = "test-secret"
description = "Testing"
regex = '''secretkey'''
```
1. create file test.txt
```
secretkey
```
1. run `pillager --config rules.toml hunt test.txt`

**Expected behavior**
test.txt contains secret

**What happens**
No secret is reported

**Screenshots**
Version 0.8.1
